-- Ajoute updated_at SEULEMENT aux tables qui ne l'ont pas
ALTER TABLE "individuals" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "individuals" ALTER COLUMN "updated_at" DROP DEFAULT;

ALTER TABLE "professionals" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "professionals" ALTER COLUMN "updated_at" DROP DEFAULT;

ALTER TABLE "item_categories" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "item_categories" ALTER COLUMN "updated_at" DROP DEFAULT;

ALTER TABLE "auctions" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "auctions" ALTER COLUMN "updated_at" DROP DEFAULT;

ALTER TABLE "bids" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "bids" ALTER COLUMN "updated_at" DROP DEFAULT;

ALTER TABLE "reviews" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "reviews" ALTER COLUMN "updated_at" DROP DEFAULT;